### PR TITLE
add pom by default to files for upload

### PR DESCRIPTION
**Pull request by a-buck**

### CODE REVIEW

**Comment by athieriot** [comment]
Very nice :)

Would you mind adding a small mention of that feature in the ```DOCS.md``` file please?
Just to round things up

**Comment by a-buck** [comment]
Thanks @athieriot , that's done!

**Comment by athieriot** [comment]
If you allow me to be a pain in the bum'. I wouldn't mind if you can squash those commits together please?

I'll take that PR anyway (don't worry) but might as well be thorough.

**Comment by a-buck** [comment]
No problem @athieriot ! Squashed :)

**Comment by athieriot** [comment]
LGTM

**Comment by msteinert** [comment]
LGTM

**Pull request merged**
